# Generated by Django 5.0.6 on 2024-07-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinocolacion',
            name='Id_tabSync',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programacion',
            name='Id_tabSync',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Id_tabSync',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
