# Generated by Django 5.0.6 on 2024-07-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_casinocolacion_id_tabsync_programacion_id_tabsync_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casinocolacion',
            name='synced_at',
        ),
        migrations.RemoveField(
            model_name='casinocolacion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='programacion',
            name='synced_at',
        ),
        migrations.RemoveField(
            model_name='programacion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='synced_at',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='casinocolacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='casinocolacion',
            name='fecha_servicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='casinocolacion',
            name='id_estado',
            field=models.IntegerField(choices=[(0, 'No visible'), (1, 'visible')], default=1),
        ),
        migrations.AlterField(
            model_name='casinocolacion',
            name='origen',
            field=models.CharField(default='local', max_length=10),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='_syncing',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='origen',
            field=models.CharField(default='local', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='activo',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='origen',
            field=models.CharField(default='local', max_length=10),
        ),
    ]
