# Generated by Django 5.0.6 on 2024-06-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0013_casinocolacion__syncing'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinocolacion',
            name='origen',
            field=models.CharField(default='nube', max_length=10),
        ),
    ]
