# Generated by Django 5.0.6 on 2024-07-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0014_casinocolacion_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='_syncing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programacion',
            name='origen',
            field=models.CharField(default='nube', max_length=10),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='_syncing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='origen',
            field=models.CharField(default='nube', max_length=10),
        ),
    ]
