# Generated by Django 5.0.6 on 2024-07-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0015_programacion__syncing_programacion_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='fecha_seleccion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
